version: '3'

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: nest_mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: data_admin
    restart: always
    ports:
      - ${ADMIN_PORT}:80
    environment:
      PMA_HOST: mysql
